set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*-256color:Tc"
set -g pane-border-lines single

# action key
set-option -g prefix C-b
set-option -g focus-events on

#### Key bindings

set-window-option -g mode-keys vi
set -g set-clipboard on
set -g allow-passthrough on
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Open current directory
bind o run-shell "open '#{pane_current_path}'"
bind e kill-pane -a

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

#### Basic settings

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set-option -g history-limit 65536
set -sg escape-time 10

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# import
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
run '~/.config/tmux/plugins/tpm/tpm'
